# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListenNow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 545)
        MainWindow.setMinimumSize(QtCore.QSize(1002, 545))
        MainWindow.setMaximumSize(QtCore.QSize(1002, 545))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/foto_perfil/logo listen Now.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.aba_perfil = QtWidgets.QFrame(self.centralwidget)
        self.aba_perfil.setGeometry(QtCore.QRect(0, 0, 229, 551))
        self.aba_perfil.setStyleSheet("background-color: rgb(17, 98, 102);")
        self.aba_perfil.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aba_perfil.setFrameShadow(QtWidgets.QFrame.Raised)
        self.aba_perfil.setObjectName("aba_perfil")
        self.foto_perfil = QtWidgets.QFrame(self.aba_perfil)
        self.foto_perfil.setGeometry(QtCore.QRect(57, 30, 120, 120))
        self.foto_perfil.setStyleSheet("background-image: url(:/foto_perfil/foto_perfil.png);\n"
"color: rgb(23, 140, 144);\n"
"border-radius: 60px;\n"
"border: 5px solid #178c90;")
        self.foto_perfil.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foto_perfil.setFrameShadow(QtWidgets.QFrame.Raised)
        self.foto_perfil.setObjectName("foto_perfil")
        self.btn_remover = QtWidgets.QPushButton(self.aba_perfil)
        self.btn_remover.setGeometry(QtCore.QRect(0, 290, 231, 41))
        self.btn_remover.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    color: white;\n"
"    font: 10pt \"Montserrat\";\n"
"    text-align: left\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #178c90;\n"
"}")
        self.btn_remover.setObjectName("btn_remover")
        self.btn_adicionar = QtWidgets.QPushButton(self.aba_perfil)
        self.btn_adicionar.setGeometry(QtCore.QRect(0, 250, 231, 41))
        self.btn_adicionar.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    color: white;\n"
"    font: 10pt \"Montserrat\";\n"
"    text-align: left\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #178c90;\n"
"}")
        self.btn_adicionar.setObjectName("btn_adicionar")
        self.lbl_nome = QtWidgets.QLabel(self.aba_perfil)
        self.lbl_nome.setGeometry(QtCore.QRect(40, 155, 161, 31))
        self.lbl_nome.setStyleSheet("font: 12pt \"Montserrat\";\n"
"color: white;")
        self.lbl_nome.setObjectName("lbl_nome")
        self.btn_adicionar_icon = QtWidgets.QPushButton(self.aba_perfil)
        self.btn_adicionar_icon.setGeometry(QtCore.QRect(190, 260, 21, 21))
        self.btn_adicionar_icon.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    background-image: url(:/aaa/adicionar.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #178c90;\n"
"}")
        self.btn_adicionar_icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Imagens e Icones/adicionar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_adicionar_icon.setIcon(icon1)
        self.btn_adicionar_icon.setIconSize(QtCore.QSize(21, 21))
        self.btn_adicionar_icon.setObjectName("btn_adicionar_icon")
        self.btn_remover_icon = QtWidgets.QPushButton(self.aba_perfil)
        self.btn_remover_icon.setGeometry(QtCore.QRect(190, 300, 21, 21))
        self.btn_remover_icon.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    background-image: url(:/aaa/remover.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #178c90;\n"
"}")
        self.btn_remover_icon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Imagens e Icones/remover.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_remover_icon.setIcon(icon2)
        self.btn_remover_icon.setIconSize(QtCore.QSize(21, 21))
        self.btn_remover_icon.setObjectName("btn_remover_icon")
        self.btn_download = QtWidgets.QPushButton(self.aba_perfil)
        self.btn_download.setGeometry(QtCore.QRect(0, 330, 231, 41))
        self.btn_download.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    color: white;\n"
"    font: 10pt \"Montserrat\";\n"
"    text-align: left\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #178c90;\n"
"}")
        self.btn_download.setObjectName("btn_download")
        self.btn_download_icon = QtWidgets.QPushButton(self.aba_perfil)
        self.btn_download_icon.setGeometry(QtCore.QRect(190, 340, 21, 21))
        self.btn_download_icon.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    \n"
"    background-image: url(:/aaa/cloud-download-2.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #178c90;\n"
"}")
        self.btn_download_icon.setText("")
        self.btn_download_icon.setIcon(icon2)
        self.btn_download_icon.setIconSize(QtCore.QSize(21, 21))
        self.btn_download_icon.setObjectName("btn_download_icon")
        self.btn_home = QtWidgets.QPushButton(self.aba_perfil)
        self.btn_home.setGeometry(QtCore.QRect(0, 210, 231, 41))
        self.btn_home.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    color: white;\n"
"    font: 10pt \"Montserrat\";\n"
"    text-align: left\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #178c90;\n"
"}\n"
"\n"
"QPushButton_6 {\n"
"    \n"
"    background-color: rgb(0, 85, 255);\n"
"}")
        self.btn_home.setObjectName("btn_home")
        self.btn_home_icon = QtWidgets.QPushButton(self.aba_perfil)
        self.btn_home_icon.setGeometry(QtCore.QRect(190, 220, 21, 21))
        self.btn_home_icon.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    \n"
"    \n"
"    background-image: url(:/aaa/home.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #178c90;\n"
"}")
        self.btn_home_icon.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Imagens e Icones/playlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home_icon.setIcon(icon3)
        self.btn_home_icon.setIconSize(QtCore.QSize(21, 21))
        self.btn_home_icon.setObjectName("btn_home_icon")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(220, 460, 781, 91))
        self.frame_2.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbl_nome_musica = QtWidgets.QLabel(self.frame_2)
        self.lbl_nome_musica.setGeometry(QtCore.QRect(90, 20, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_nome_musica.setFont(font)
        self.lbl_nome_musica.setStyleSheet("font: 12pt \"Montserrat\";\n"
"color: #178c90;")
        self.lbl_nome_musica.setObjectName("lbl_nome_musica")
        self.btn_volume = QtWidgets.QPushButton(self.frame_2)
        self.btn_volume.setGeometry(QtCore.QRect(590, 35, 21, 21))
        self.btn_volume.setStyleSheet("QPushButton {\n"
"border: 0px solid;\n"
"background-image: url(:/aaa/auto-falante.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-image: url(:/aaa/auto-falante_hover.png);\n"
"}")
        self.btn_volume.setText("")
        self.btn_volume.setIconSize(QtCore.QSize(30, 30))
        self.btn_volume.setObjectName("btn_volume")
        self.frame_musica = QtWidgets.QFrame(self.frame_2)
        self.frame_musica.setGeometry(QtCore.QRect(20, 10, 60, 60))
        self.frame_musica.setStyleSheet("background-image: url(:/aaa/musica.png);")
        self.frame_musica.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_musica.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_musica.setObjectName("frame_musica")
        self.btn_voltar = QtWidgets.QPushButton(self.frame_2)
        self.btn_voltar.setGeometry(QtCore.QRect(324, 28, 30, 30))
        self.btn_voltar.setStyleSheet("QPushButton {\n"
"border: 0px solid;\n"
"background-image: url(:/aaa/passar para tras.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-image: url(:/aaa/passar para tras_hover.png);\n"
"}")
        self.btn_voltar.setText("")
        self.btn_voltar.setIconSize(QtCore.QSize(30, 30))
        self.btn_voltar.setObjectName("btn_voltar")
        self.lbl_nome_artista = QtWidgets.QLabel(self.frame_2)
        self.lbl_nome_artista.setGeometry(QtCore.QRect(90, 40, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_nome_artista.setFont(font)
        self.lbl_nome_artista.setStyleSheet("font: 10pt \"Montserrat\";\n"
"color: #178c90;")
        self.lbl_nome_artista.setObjectName("lbl_nome_artista")
        self.volume_slider = QtWidgets.QSlider(self.frame_2)
        self.volume_slider.setGeometry(QtCore.QRect(620, 35, 100, 22))
        self.volume_slider.setStyleSheet("QSlider::groove:horizontal { \n"
"    background-color: rgb(17, 98, 102);\n"
"    height: 10px;\n"
"    border-radius: 4px;\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"}\n"
"\n"
"QSlider::handle:horizontal { \n"
"    background-color: #178c90; \n"
"    border: 2px solid #178c90; \n"
"    width: 11px; \n"
"    height: 16px;\n"
"    margin-top: -3px; \n"
"    margin-bottom: -3px;  \n"
"    line-height: 20px; \n"
"    border-radius: 7px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover { \n"
"    border-radius: 7px; \n"
"}\n"
"")
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.btn_avancar = QtWidgets.QPushButton(self.frame_2)
        self.btn_avancar.setGeometry(QtCore.QRect(450, 28, 30, 30))
        self.btn_avancar.setStyleSheet("QPushButton {\n"
"border: 0px solid;\n"
"background-image: url(:/aaa/passar para frentre.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-image: url(:/aaa/passar para frentre_hover.png);\n"
"}")
        self.btn_avancar.setText("")
        self.btn_avancar.setIconSize(QtCore.QSize(30, 30))
        self.btn_avancar.setObjectName("btn_avancar")
        self.btn_pausar_play = QtWidgets.QPushButton(self.frame_2)
        self.btn_pausar_play.setGeometry(QtCore.QRect(372, 13, 60, 60))
        self.btn_pausar_play.setStyleSheet("QPushButton {\n"
"border: 0px solid;\n"
"background-image: url(:/aaa/pause.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-image: url(:/aaa/pause_hover.png);\n"
"}\n"
"\n"
"")
        self.btn_pausar_play.setText("")
        self.btn_pausar_play.setIconSize(QtCore.QSize(30, 30))
        self.btn_pausar_play.setObjectName("btn_pausar_play")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(230, 0, 771, 461))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.lbl_bem_vindo = QtWidgets.QLabel(self.home)
        self.lbl_bem_vindo.setGeometry(QtCore.QRect(130, 20, 501, 51))
        self.lbl_bem_vindo.setStyleSheet("font: 24pt \"Montserrat\";\n"
"color: #178c90;")
        self.lbl_bem_vindo.setObjectName("lbl_bem_vindo")
        self.label = QtWidgets.QLabel(self.home)
        self.label.setGeometry(QtCore.QRect(250, 390, 301, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(212, 212, 213);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.home)
        self.label_2.setGeometry(QtCore.QRect(260, 110, 271, 231))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/foto_perfil/logo listen Now.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.home)
        self.musicas = QtWidgets.QWidget()
        self.musicas.setObjectName("musicas")
        self.tableWidget = QtWidgets.QTableWidget(self.musicas)
        self.tableWidget.setGeometry(QtCore.QRect(60, 80, 651, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.musicas_adicionadas = QtWidgets.QLabel(self.musicas)
        self.musicas_adicionadas.setGeometry(QtCore.QRect(220, 10, 341, 41))
        self.musicas_adicionadas.setStyleSheet("font: 24pt \"Montserrat\";\n"
"color: #178c90;")
        self.musicas_adicionadas.setObjectName("musicas_adicionadas")
        self.stackedWidget.addWidget(self.musicas)
        self.downloader = QtWidgets.QWidget()
        self.downloader.setObjectName("downloader")
        self.listennow_downloader = QtWidgets.QLabel(self.downloader)
        self.listennow_downloader.setGeometry(QtCore.QRect(210, 130, 391, 41))
        self.listennow_downloader.setStyleSheet("font: 24pt \"Montserrat\";\n"
"color: #178c90;")
        self.listennow_downloader.setObjectName("listennow_downloader")
        self.btn_baixar = QtWidgets.QPushButton(self.downloader)
        self.btn_baixar.setGeometry(QtCore.QRect(600, 210, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.btn_baixar.setFont(font)
        self.btn_baixar.setStyleSheet("QPushButton {\n"
"    border: 0px solid #178c90;\n"
"    color: white;\n"
"    background-color: #178c90;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(22, 168, 158);\n"
"}")
        self.btn_baixar.setObjectName("btn_baixar")
        self.line_link = QtWidgets.QLineEdit(self.downloader)
        self.line_link.setGeometry(QtCore.QRect(112, 210, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.line_link.setFont(font)
        self.line_link.setStyleSheet("border: 2px solid #178c90;\n"
"color: rgb(124, 124, 124);")
        self.line_link.setInputMask("")
        self.line_link.setText("")
        self.line_link.setFrame(True)
        self.line_link.setCursorPosition(0)
        self.line_link.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.line_link.setClearButtonEnabled(True)
        self.line_link.setObjectName("line_link")
        self.listennow_downloader_2 = QtWidgets.QLabel(self.downloader)
        self.listennow_downloader_2.setGeometry(QtCore.QRect(260, 320, 111, 31))
        self.listennow_downloader_2.setStyleSheet("font: 16pt \"Montserrat\";\n"
"color: #178c90;")
        self.listennow_downloader_2.setObjectName("listennow_downloader_2")
        self.btn_baixar_2 = QtWidgets.QPushButton(self.downloader)
        self.btn_baixar_2.setGeometry(QtCore.QRect(380, 320, 141, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.btn_baixar_2.setFont(font)
        self.btn_baixar_2.setStyleSheet("QPushButton {\n"
"    border: 0px solid #178c90;\n"
"    color: white;\n"
"    background-color: #178c90;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(22, 168, 158);\n"
"}")
        self.btn_baixar_2.setObjectName("btn_baixar_2")
        self.stackedWidget.addWidget(self.downloader)
        self.remover_musicas = QtWidgets.QWidget()
        self.remover_musicas.setObjectName("remover_musicas")
        self.lbl_selecionar_musica = QtWidgets.QLabel(self.remover_musicas)
        self.lbl_selecionar_musica.setGeometry(QtCore.QRect(200, 150, 371, 41))
        self.lbl_selecionar_musica.setStyleSheet("font: 24pt \"Montserrat\";\n"
"color: #178c90;")
        self.lbl_selecionar_musica.setObjectName("lbl_selecionar_musica")
        self.btn_deletar = QtWidgets.QPushButton(self.remover_musicas)
        self.btn_deletar.setGeometry(QtCore.QRect(230, 280, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.btn_deletar.setFont(font)
        self.btn_deletar.setStyleSheet("QPushButton {\n"
"    border: 0px solid #178c90;\n"
"    color: white;\n"
"    background-color: #178c90;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(22, 168, 158);\n"
"}")
        self.btn_deletar.setObjectName("btn_deletar")
        self.comboBox = QtWidgets.QComboBox(self.remover_musicas)
        self.comboBox.setGeometry(QtCore.QRect(170, 220, 431, 22))
        self.comboBox.setObjectName("comboBox")
        self.stackedWidget.addWidget(self.remover_musicas)
        self.frame_2.raise_()
        self.aba_perfil.raise_()
        self.stackedWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ListenNow"))
        self.btn_remover.setText(_translate("MainWindow", "     Remover Músicas"))
        self.btn_adicionar.setText(_translate("MainWindow", "     Adicionar Músicas"))
        self.lbl_nome.setText(_translate("MainWindow", "Geovani Debastiani"))
        self.btn_download.setText(_translate("MainWindow", "     Baixar Músicas"))
        self.btn_home.setText(_translate("MainWindow", "     Home"))
        self.lbl_nome_musica.setText(_translate("MainWindow", "Música"))
        self.lbl_nome_artista.setText(_translate("MainWindow", "Artista"))
        self.lbl_bem_vindo.setText(_translate("MainWindow", "Seja Bem-Vindo ao ListenNow"))
        self.label.setText(_translate("MainWindow", "Nenhuma música adicionada"))
        self.musicas_adicionadas.setText(_translate("MainWindow", "Músicas Adicionadas"))
        self.listennow_downloader.setText(_translate("MainWindow", "ListenNow Downloader"))
        self.btn_baixar.setText(_translate("MainWindow", "Baixar"))
        self.line_link.setPlaceholderText(_translate("MainWindow", " Insira o link do Youtube aqui..."))
        self.listennow_downloader_2.setText(_translate("MainWindow", "Salvar em:"))
        self.btn_baixar_2.setText(_translate("MainWindow", "Selecionar"))
        self.lbl_selecionar_musica.setText(_translate("MainWindow", "Selecione uma música"))
        self.btn_deletar.setText(_translate("MainWindow", "Deletar"))

from View.PY import file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ListenNow
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
